fix: Ensure $HOME is set in Tesseracts and has appropriate permissions (#490)
#### Relevant issue or PR

We started seeing weird warnings (and even errors) on situations like
the following: imagine you have a Tesseract which depends on, say,
matplotlib and arviz.

It builds fine
```
$ tesseract --loglevel=DEBUG build someimage
...
[+] #27 [run_stage 12/12] RUN _TESSERACT_IS_BUILDING=1 /tesseract/entrypoint.sh tesseract-runtime check
...
 [+] #27 3.370 ✅ Tesseract API check successful ✅
...
```
But it fails when one tries to use it. The reason why emerges if we do
this:
```bash
$ tesseract serve someimage:0.1.1
 [i] Waiting for Tesseract to start...
 [i] Serving Tesseract at http://127.0.0.1:55544
 [i] View Tesseract: http://127.0.0.1:55544/docs
 [i] Container ID: 7270fe36d273a05bfd3c0571d72bbd841c132d1fb3cd0a51d3e290b21a6fabbb
 [i] Name: dreamy_hoover
 [i] Entrypoint: ['/tesseract/entrypoint.sh', 'tesseract-runtime']
 [i] View Tesseract: http://127.0.0.1:55544/docs
 [i] Tesseract container name, use it with 'tesseract teardown' command: dreamy_hoover
{"container_name": "dreamy_hoover", "containers": [{"name": "dreamy_hoover", "port": "55544", "ip": "127.0.0.1", "networks": {"bridge": {"ip": "172.17.0.3", "port": "55544"}}}]}

$ docker exec -it dreamy_hoover python 
Python 3.11.2 (main, Apr 28 2025, 14:11:48) [GCC 12.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import arviz as az
mkdir -p failed for path /.config/matplotlib: [Errno 13] Permission denied: '/.config'
Matplotlib created a temporary cache directory at /tmp/matplotlib-_4i954jx because there was an issue with the default path (/.config/matplotlib); it is highly recommended to set the MPLCONFIGDIR environment variable to a writable directory, in particular to speed up the import of Matplotlib and to better support multiprocessing.
Traceback (most recent call last):
  File "/usr/lib/python3.11/pathlib.py", line 1117, in mkdir
    os.mkdir(self, mode)
FileNotFoundError: [Errno 2] No such file or directory: '/.cache/arviz'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/python-env/lib/python3.11/site-packages/arviz/__init__.py", line 61, in <module>
    _warn_once_per_day()
  File "/python-env/lib/python3.11/site-packages/arviz/__init__.py", line 39, in _warn_once_per_day
    warning_dir.mkdir(exist_ok=True, parents=True)
  File "/usr/lib/python3.11/pathlib.py", line 1121, in mkdir
    self.parent.mkdir(parents=True, exist_ok=True)
  File "/usr/lib/python3.11/pathlib.py", line 1117, in mkdir
    os.mkdir(self, mode)
PermissionError: [Errno 13] Permission denied: '/.cache'
```

Here we see two things:
1. These libraries don't use the data in /etc/passwd to infer where the
home folder is, but read `$HOME` (that's why stuff like `/.cache`
appears instead of `/tesseract/.cache`.
2. If we just set $HOME to `/tesseract`, a user with uid:gid 9999:9999
will already have created folders like `~/.config` (and some subfolders)
during the build-time sanity check, creating more permissions issues.
Moreover, other stuff (like `__pycache__`) will be embedded in the image
by default. In principle, cleaning up the image after the sanity check
runs is possible, but in practice there could be a number of arbitrary
things that are written in this stage which are hard to clean up.

We initially tried to, aside from setting HOME in the Dockerfile,
extract the runtime check from the Dockerfile and do it at the engine
level. Then @dionhaefner observed that in some places the fact that the
pycache is already present in the image is actually a positive thing. So
we decided to just chmod 777 the whole /tesseract folder and subfolders
after runtime checks run.

#### Description of changes

  *  Set HOME env variable to `/tesseract/` in the Dockerfile
  *  chmod -R 777 /tesseract

#### Testing done

CI