doc: update rocket fin example to recent versions of Tesseract (#541)
#### Relevant issue or PR

N/A

### Description of changes

- Pre-serve `bars_3d` as a persistent container and pass it via URL
reference `({"type": "url", ...})` instead of `{"type": "image", ...}`,
preventing a new container being spawned on every optimization iteration
- Serving design_tess with `design_tess = Tesseract.from_image("sdf_fd",
network=NETWORK, network_alias="sdf_fd")`
- Updated Neumann BCs mask to cover all nodes at the end of the rod
(only half of z plane points were selected by the mask)
- Replaced `umfpack_solver` (giving NaNs) with `petsc_solver` with LU
factorization (see more details below)
- `sdf_fd`, `bars_3d`: upgrade `pyvista` (unpinned) to fix `vtk` wheel
incompatibility with Python 3.11
- Updated pinned requirements deps
- Updated to tesseract-core==1.6.0`
- Added `tqdm` in the optimization loop
- `tesseract_config.yaml`: change `target_platform` from `linux/x86_64`
to native to avoid QEMU emulation on Apple Silicon

#### NaN issue
Suddently `jax_fem` started to consistently produce NaNs in the jax-fem
solver in the forward pass

```python
compliance = apply_tesseract(
    fem_tess,
    {
        "rho": jnp.expand_dims(mesher_out["mesh_cell_values"], axis=-1),
        "hex_mesh": hex_mesh,
        "dirichlet_mask": dirichlet_mask,
        "dirichlet_values": jnp.array([0.0]),
        "von_neumann_mask": von_neumann_mask,
        "von_neumann_values": jnp.array([[0.0, 0.0, 1.0]]) / jnp.sum(von_neumann_mask),
    },
)["compliance"]
print(f"Compliance: {compliance:.4f}")
```
with error
```python
File "/python-env/lib/python3.12/site-packages/jax_fem/solver.py", line 415, in solver
    assert np.all(np.isfinite(res_val)), f"res_val contains NaN, stop the program!"
AssertionError: res_val contains NaN, stop the program!
```

### Testing done

- Running notebook manually
- **NOTE** that the results looks different now

---------

Co-authored-by: Dion Häfner <dion.haefner@simulation.science>